//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspLicores
{
    using System;
    using System.Collections.Generic;
    
    public partial class licores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public licores()
        {
            this.detalle_Factura = new HashSet<detalle_Factura>();
        }
    
        public int idLicor { get; set; }
        public byte[] nombre { get; set; }
        public decimal precio { get; set; }
        public int cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_Factura> detalle_Factura { get; set; }
    }
}
