//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspLicores
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidad : DbContext
    {
        public Entidad()
            : base("name=Entidad")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detalle_Factura> detalle_Factura { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<licores> licores { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
